### ISSUE TITLE
Bug-Report Semu , func_to_rank_dec.sort(key=lambda x: len(this_mutants_by_funcs[x], reversed=True)), len takes no keyword arguments.

### ISSUE THREAD

**Issue by Marvinmw** [thierry-tct/muteria#3]
In muteria/drivers/testgeneration/tools_by_languages/c/semu/semu.py,
       func_to_rank_dec.sort(key=lambda x: len(this_mutants_by_funcs[x], \
                                                                reversed=True)), len takes no keyword arguments.

12/20/2019 01:49:23 AM [root] [DEBUG] Logging Debug Level
12/20/2019 01:49:25 AM [root] [INFO]
12/20/2019 01:49:25 AM [root] [INFO] executor: Running for Test tool types = ['USE_ONLY_CODE']
12/20/2019 01:49:25 AM [root] [INFO]
12/20/2019 01:49:25 AM [root] [INFO]
12/20/2019 01:49:25 AM [root] [INFO] executor: Running for Test tool types = ['USE_CODE_AND_TESTS']
12/20/2019 01:49:25 AM [root] [INFO]
12/20/2019 01:49:25 AM [root] [INFO] checkpoint_tasks:NEXT_TODO:['TESTS_GENERATION_USING_CRITERIA']
12/20/2019 01:49:25 AM [root] [DEBUG] # Generating tests with semu ...
Traceback (most recent call last):
  File "/usr/local/bin/muteria", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/muteria/cli/cli.py", line 111, in main
    CliUserInterface.cmd_main()
  File "/usr/local/lib/python3.6/dist-packages/muteria/cli/cli.py", line 105, in cmd_main
    ctrl.raw_config_main(raw_config=cmd_raw_conf)
  File "/usr/local/lib/python3.6/dist-packages/muteria/controller/main_controller.py", line 95, in raw_config_main
    self.main(final_config=final_conf)
  File "/usr/local/lib/python3.6/dist-packages/muteria/controller/main_controller.py", line 113, in main
    exec_obj.main()
  File "/usr/local/lib/python3.6/dist-packages/muteria/controller/executor.py", line 304, in main
    self._execute_task(task)
  File "/usr/local/lib/python3.6/dist-packages/muteria/controller/executor.py", line 387, in _execute_task
    test_tool_type_list=self.cp_data.test_types)
  File "/usr/local/lib/python3.6/dist-packages/muteria/drivers/testgeneration/meta_testcasetool.py", line 684, in generate_tests
    max_time=max_time)
  File "/usr/local/lib/python3.6/dist-packages/muteria/drivers/testgeneration/base_testcasetool.py", line 517, in generate_tests
    max_time=max_time)
  File "/usr/local/lib/python3.6/dist-packages/muteria/drivers/testgeneration/tools_by_languages/c/klee/klee.py", line 392, in _do_generate_tests
    self._call_generation_run(prog, list(args))
  File "/usr/local/lib/python3.6/dist-packages/muteria/drivers/testgeneration/tools_by_languages/c/semu/semu.py", line 140, in _call_generation_run
    func_to_rank_dec.sort(key=lambda x: len(this_mutants_by_funcs[x], \
  File "/usr/local/lib/python3.6/dist-packages/muteria/drivers/testgeneration/tools_by_languages/c/semu/semu.py", line 141, in <lambda>
    reversed=True))
TypeError: len() takes no keyword arguments
Error (/home/cmtools/run.sh): post failed!
Run End /work/data/ln/3e0dff3925b5e521cae468087950e85b60002d1c

>

**Comment by thierry-tct** [comment]
fixed
